FROM node:21-slim

WORKDIR /usr/src/app

COPY package.json ./
COPY pnpm-lock.yaml ./
COPY prisma ./prisma

RUN apt-get update && apt-get install -y  libreoffice \
  fonts-dejavu \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* && \
  npm install -g pnpm && pnpm install && \
  pnpm prisma:generate --schema prisma/schema.prisma

COPY . .

